FROM golang:1.21 AS builder

COPY . /build
WORKDIR /build
RUN cd cmd/chatbot && GOPROXY=https://goproxy.io go build

FROM debian:stable-slim

RUN mkdir /app
COPY --from=builder /build/cmd/chatbot/chatbot /app/
COPY --from=builder /build/cmd/chatbot/config.yml /app/
WORKDIR /app
CMD ["./chatbot"]