FROM golang:1.21 AS builder

COPY . /build
WORKDIR /build
RUN cd cmd/simserver && GOPROXY=https://goproxy.io go build

FROM debian:stable-slim

RUN mkdir /app
COPY --from=builder /build/cmd/simserver/simserver /app/
COPY --from=builder /build/cmd/simserver/reviews.json /app/
WORKDIR /app
CMD ["./simserver"]